# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database tracker1' -U postgres

cache:
  directories:
    - $HOME/.m2

    # используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -vitvit1@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    -CODECOV_TOKEN="2139699c-00be-4114-819b-da1bb122c4cd"
